# Generated by Django 5.0.1 on 2025-12-17 22:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('water_body_type', models.CharField(choices=[('LAKE', 'Lake'), ('RIVER', 'River')], max_length=20)),
                ('latitude', models.FloatField(help_text='Latitude coordinate', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Longitude coordinate', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('description', models.TextField(blank=True)),
                ('regulatory_body', models.CharField(blank=True, help_text='EPA region or local authority', max_length=200)),
                ('monitoring_start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterQualityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the measurement was taken')),
                ('ph', models.FloatField(help_text='pH level (0-14)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('dissolved_oxygen', models.FloatField(help_text='Dissolved oxygen in mg/L', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('temperature', models.FloatField(help_text='Water temperature in Celsius')),
                ('notes', models.TextField(blank=True)),
                ('sample_latitude', models.FloatField(blank=True, help_text='Latitude where sample was taken', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('sample_longitude', models.FloatField(blank=True, help_text='Longitude where sample was taken', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='monitoring.waterbody')),
            ],
        ),
    ]
