# Generated by Django 5.0.1 on 2025-12-15 20:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('water_body_type', models.CharField(choices=[('LAKE', 'Lake'), ('RIVER', 'River'), ('RESERVOIR', 'Reservoir'), ('POND', 'Pond'), ('STREAM', 'Stream'), ('OCEAN', 'Ocean/Bay')], max_length=20)),
                ('latitude', models.FloatField(help_text='Latitude coordinate', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Longitude coordinate', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('description', models.TextField(blank=True)),
                ('regulatory_body', models.CharField(blank=True, help_text='EPA region or local authority', max_length=200)),
                ('monitoring_start_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Water Bodies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaterQualityMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the measurement was taken')),
                ('ph', models.FloatField(help_text='pH level (0-14)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('dissolved_oxygen', models.FloatField(help_text='Dissolved oxygen in mg/L', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('temperature', models.FloatField(help_text='Water temperature in Celsius')),
                ('turbidity', models.FloatField(help_text='Turbidity in NTU (Nephelometric Turbidity Units)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('nitrates', models.FloatField(help_text='Nitrate concentration in mg/L', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('phosphates', models.FloatField(help_text='Phosphate concentration in mg/L', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ecoli_count', models.IntegerField(help_text='E. coli bacterial count in CFU/100mL', validators=[django.core.validators.MinValueValidator(0)])),
                ('measured_by', models.CharField(help_text='Name of field researcher', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('sample_latitude', models.FloatField(blank=True, help_text='Latitude where sample was taken', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('sample_longitude', models.FloatField(blank=True, help_text='Longitude where sample was taken', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='monitoring.waterbody')),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['-measured_at'], name='monitoring__measure_4e3487_idx'), models.Index(fields=['water_body', '-measured_at'], name='monitoring__water_b_3431c6_idx')],
            },
        ),
    ]
