# Generated by Django 5.0.1 on 2025-12-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbody',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='waterqualitymeasurement',
            name='sample_latitude',
        ),
        migrations.RemoveField(
            model_name='waterqualitymeasurement',
            name='sample_longitude',
        ),
    ]
